### ISSUE TITLE
basemodel.predict(temp_x)

### ISSUE THREAD

**Issue by ythwilam** [Walleclipse/ChineseAddress_OCR#1]
执行这一步的时候报错：
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a reorder primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:813
	 [[Node: concatenate_49/concat = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2d_55/convolution, conv2d_56/BiasAdd, concatenate_49/concat/axis, conv2d_55/convolution:2, conv2d_56/BiasAdd:2, DMT/_10)]]

basemodel.load_weights(modelPath) 这一步没问题，在预测的时候报错了，请问这个是什么原因啊
谢谢

**Comment by Walleclipse** [comment]
I think this issue was caused by tensorflow version incompatibility.Whar is your tf version? Please try to other tf version and you can refer https://github.com/tensorflow/tensorflow/issues/17494
