### ISSUE TITLE
识别结果全都是错的，类似乱码

### ISSUE THREAD

**Issue by pingzi5233** [Walleclipse/ChineseAddress_OCR#11]
您好，想问一下，为什么识别结果会是这样的？全都是乱码一样，请问知道为什么吗？还是我测试的时候哪里设置的不对吗？
识别结果为：
![image](https://user-images.githubusercontent.com/48909056/59186725-35812980-8ba6-11e9-8b41-c13f85524787.png)

实际测试图像为：
![demo](https://user-images.githubusercontent.com/48909056/59186736-3c0fa100-8ba6-11e9-8a70-7ccaaf5ed024.jpg)

**Comment by Walleclipse** [comment]
这个项目主要是识别地址字段。
`demo_final.py` 里面会过滤掉非地址字段。如果你想识别非地址字段， 你只需要输出 `demo_final.py`  里面的第50行 `result, image_framed = ocr_whole.model(image)` 中的 ` result`  。
但是由于此模型主要在地址数据上进行训练的，所以不保证非地址的识别效果。
如果还是乱码那么可能是python的编码问题，你考虑一下 把所有输入输出都编码成 `utf-8` 格式

**Comment by pingzi5233** [comment]
嗯好，我试试，感谢
