### ISSUE TITLE
检测+识别

### ISSUE THREAD

**Issue by yunhai0920** [Walleclipse/ChineseAddress_OCR#2]
你好 请教几个问题
1.请问检测那块的数据集是重新用具体所需图像标注训练还是直接用ctpn作者提供的数据voc啊
2.看项目介绍像是商户的证件，请问检测之前是对原图做个区域选择 还是直接全部检测啊，因为看到你最终只是检测公司地址这一块或者说预测前是否做了一些预处理呢 。
3.densenet识别那块 也是直接用原作者给出的数据进行训练的吗？ 我看你给出了一个全是公司地址的一个测试集

**Comment by Walleclipse** [comment]
你好
1. 我们这个模型用了我们自己的数据集从0开始训练，主要是商户证件数据，然后进行了人工标注
2. 直接把原图输入进网络也可以，但是效果不一定好，可以用比较简单的方法先切图
3. 识别那一块也用了我们自己的数据集，但是用到了预训练模型
PS： 由于所有训练数据都是我们自己的数据，所以这个模型是强任务相关的，在我们那个任务上效果很好，其他任务需要用其他任务的数据进行训练
