### ISSUE TITLE
请问这个工程只能在GPU的环境下运行吗？

### ISSUE THREAD

**Issue by batumgl** [Walleclipse/ChineseAddress_OCR#21]
我这边虚拟机上没有GPU，仅能使用CPU进行计算，这个工程只能在GPU的环境下运行吗？如果可以在仅CPU的环境下运行，我需要改哪些文件呢？

**Comment by Walleclipse** [comment]
你好，在CPU上也可以运行，只是速度会很慢。但是要注意要有足够的内存空间。
一般来说不许要特别进行修改。

**Comment by batumgl** [comment]
> 
> 
> 你好，在CPU上也可以运行，只是速度会很慢。但是要注意要有足够的内存空间。
> 一般来说不许要特别进行修改。

收到，谢谢！

**Comment by batumgl** [comment]
我在运行 demo_final.py 文件时，提示 No module named 'classifier' ，我定位到问题出在 tgrocery 这个库里，看起来这个库是使用 python2 版本编写的，例如：该库在其 converter.py 文件中 import cPickle ，cPickle 库似乎是 python2 的库，在 python3 版本中已被 pickle 库代替。我根据 python3 的编程规范修改了 tgrocery 中的部分源代码，运行 demo_final.py 文件时不在报错，但我根据 README.md 文件编写 Simple_Use.py 时，依然报 NameError: name 'unicode' is not defined ，具体错误信息如下：

![微信截图_20201201190510](https://user-images.githubusercontent.com/24230932/100732963-76a77200-3408-11eb-9886-f421e6a81f0b.png)

错误定位到 tgrocery 库的 classifier.py 文件的53行，其上下文如下：

![2](https://user-images.githubusercontent.com/24230932/100733053-9474d700-3408-11eb-8d9d-4d460fcc792d.png)

请问我是否应该修改 tgrocery 的源代码？或者我应该如何正确操作以使工程正常使用？

**Comment by Walleclipse** [comment]
你好，有两种选择，
1）你可能需要修改tgrocery的源代码，主要是可能需要改一些py2与py3的编码问题，比如说你可以试试直接把出错的tgrocery 库的` classifier.py` 文件的53-54行注释掉。py3中没有 `unicode`， py3中一般是 `str`
2）`demo_final.py `中 tgrocery的作用就是判断一段文字是否为地址。
其中 33-44行就是训练模型，你可以把tgrocery替换成任意的机器学习模型，比如说SVM， RF等。利用地址数据 `pkl_data/address1.pkl` 与非地址数据 `pkl_data/others1.pkl` 进行二分类模型的训练。
PS：为了验证该项目的其他部分是否运行正常，你可以暂时 把 `demo_final.py` 中出错的 `predict_result = grocery.predict(string2)` 注释掉，并且换成 `predict_result = 'address'`

**Comment by batumgl** [comment]
收到，已能正常运行，谢谢！
