### ISSUE TITLE
window环境运行

### ISSUE THREAD

**Issue by zjiepeng** [Walleclipse/ChineseAddress_OCR#22]
window下可以运行吗？会报bbox导入错误的问题

**Comment by Walleclipse** [comment]
你好，
我没有在windows下运行过，不太清楚。
bbox导入错误跟CTPN有关，你可以到原CTPN的[repo](https://github.com/eragonruan/text-detection-ctpn)下提问。我们的文字检测部分直接用了这个原来的[repo](https://github.com/eragonruan/text-detection-ctpn).
