### ISSUE TITLE
CTPN

### ISSUE THREAD

**Issue by msxx001** [Walleclipse/ChineseAddress_OCR#4]
你好，打扰一下，在ctpn模型中，在conv5进行3x3，步长为1的滑窗
。为什么得到的3x3xC的向量？卷积得到不是1*1*C的向量吗？

**Comment by Walleclipse** [comment]
你好呀。不好意思，没太理解你具体说的是哪里呢？
一般情况下，
输入图片大小是 $W \times H \times C_in$  
卷积核Filter 大小 $F_W \times F_H $ ， Filter个数为 $k$
步长 $S_W \times S_H $ , 填充0 padding的个数  $P_W \times P_H $
则输出图片的宽和长分别为
$W_{out} = (W − F_W + 2 \cdot P_W )/S_W+1 $  
$ H_{out} = (H − F_H + 2 \cdot P_H )/S_H+1 $  
输出通道数为 $C_{out} =k $
tensorflow有 ‘same’ 和 'valid'两种padding模式，其中
'same': $W_{out} = \lceil W /S_W \rceil $   
'valid': $W_{out} = \lceil  (W− F_W +1 )/S_W \rceil  $
