### ISSUE TITLE
关于如何部署在微信小程序

### ISSUE THREAD

**Issue by xdwjc** [Walleclipse/ChineseAddress_OCR#6]
博主您好，我是在校一名学生，之前也看了YCG的这个ctpn+densenet+ctc的ocr项目，也自己训练了模型，现在想学习您一样在微信小程序上这样部署，感觉比较炫酷，恕小弟唐突了，不知能否方便加下您的qq或者微信，小弟想跟您学习一下，我的qq是1164757353，微信是wjc953368

**Comment by Walleclipse** [comment]
好的，
其实微信小程序部分是我的队友做的，我不太了解。
我加你qq吧
