### ISSUE TITLE
tgrocery问题

### ISSUE THREAD

**Issue by hufangjian** [Walleclipse/ChineseAddress_OCR#7]
请问是python3版本的吗？我运行的时候出现下面问题。
  File "demo_final.py", line 10, in <module>
    from tgrocery import Grocery
  File "/root/anaconda3/lib/python3.6/site-packages/tgrocery/__init__.py", line 1, in <module>
    from converter import *

**Comment by Walleclipse** [comment]
你好，
这个repo就是python3. 
可能是你下载的tgrocery 版本和我的不一样造成的的。你可以查看处于错的地方  converter.py，然后试着修改成python3 版本。
比如 import cPickle -> import pickle
或者可以不用tgrocery，你可以利用light gbm 训练一个二分类器（分类是地址还是非地址）。

**Comment by JJoohhnnn** [comment]
请问你这个问题解决了吗 ？
importerror: no model named 'converter'
