### ISSUE TITLE
运行demo_final.py怎么输入图片呢

### ISSUE THREAD

**Issue by gitmessage** [Walleclipse/ChineseAddress_OCR#8]
运行 demo_final.py 。以下提示，怎么输入图片呢？
<img width="604" alt="Snipaste_2019-03-24_17-36-11" src="https://user-images.githubusercontent.com/24708498/54877594-a6dcf600-4e5b-11e9-976d-b6c9065e6553.png">

**Comment by gitmessage** [comment]
楼主如果方便可以加我的qq:110060531 多谢

**Comment by Walleclipse** [comment]
你好，
demo_final.py 里面 有个函数 def demo_flask(image_file). 调用这个函数传入图片地址就可以。
比如：
```
from demo_final import demo_flask
image_file="./demo.png"
output_file,ret_total = demo_flask(image_file)
print('Recongition Result:')
print(ret_total)
```

**Comment by gitmessage** [comment]
按您的运行，依然是上述错误，重新安装了一遍。
报以下错误的时候，安装 pip install converter发现是2.X版本的，才会导致的上述错误（图片中）。请问，3.x的converter如何安装？
多谢！

   File "demo.py", line 1, in <module>
    from demo_final import demo_flask
  File "/ground/ChineseAddress_OCR/demo_final.py", line 10, in <module>
    from tgrocery import Grocery
  File "/usr/local/lib/python3.6/dist-packages/tgrocery/__init__.py", line 1, in <module>
    from converter import *
ModuleNotFoundError: No module named 'converter'

**Comment by gitmessage** [comment]
<img width="902" alt="error" src="https://user-images.githubusercontent.com/24708498/55226534-2c8fe580-5250-11e9-8caf-f78d96235649.png">

**Comment by Walleclipse** [comment]
你好，你可以查看一下 [issue 7](https://github.com/Walleclipse/ChineseAddress_OCR/issues/7#issuecomment-475120762)
查看出错的地方修改成python3格式（主要是修改print 函数）。比如图示中的部分改成
`print("This is the metric converter")`
或者可以不用tgrocery，你可以利用其他分类器（比如 light gbm） 训练一个二分类器（分类是地址还是非地址）

**Comment by gitmessage** [comment]
修改成了python3的语法。运行 demo_final.py ，就是第一个的图片，不能识别图片中的文字了

**Comment by Walleclipse** [comment]
如果输出是空的话，那很有可能把所有识别的文字判断成了非地址。你可以查看 demo_final.py 的第25行
`result, image_framed = ocr_whole.model(image)`
这里的result就是OCR模块识别所有文字的结果。随后识别的所有文字会经过地址判断器进行筛选成只包括地址的`ret_total`。非地址文字都会被过滤掉。
你查看一下是这里的OCR输出的`result`是空的还是最后的`ret_total`是空的
