### ISSUE TITLE
虚拟机下使用cpu运行

### ISSUE THREAD

**Issue by wyz960616** [Walleclipse/ChineseAddress_OCR#9]
打扰下，没有太搞懂给的cpu链接示例；跟着如下描述修改：
To use cpu only, I follow the author's instruction and make the following modifications:
(1) Set "USE_GPU_NMS " in the file ./ctpn/text.yml as "False"
(2) Set the "__C.USE_GPU_NMS" in the file ./lib/fast_rcnn/config.py as "False";
(3) Comment out the line "from lib.utils.gpu_nms import gpu_nms" in the file ./lib/fast_rcnn/nms_wrapper.py;
(4) To rebuild the setup.py:
最后的setup.py步骤应该与本项目应该无关；
在修改上面三个参数后运行 demo_final.py，在读取Vggnet_fast_rcnn_iter_86000；显示未找到/data/share/chinese_ocr/ctpn/checkpoints。
老师可能借用这个为baseline启动一个项目，目前因为设备问题，只有虚拟机没法用显卡。而对方近期需要演示一下demo。

**Comment by Walleclipse** [comment]
你好。你可以检查一下checkpint的路径，是否真的存在。
具体问题你可以查看 [text-detection-ctpn-issues](https://github.com/eragonruan/text-detection-ctpn/issues/43#issue-274884682)。这个是原作者的github。具体的我也不是很清楚，你可以在原作者的github下提问
